// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPDE5nABFgITagtUNJCM5KWKrTfIlu2pA',
    appId: '1:428238808676:web:a60d9708754754f9b72171',
    messagingSenderId: '428238808676',
    projectId: 'to-do-application-6d1ef',
    authDomain: 'to-do-application-6d1ef.firebaseapp.com',
    storageBucket: 'to-do-application-6d1ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPCQTDNMpp9id2jiaxgwgLG4AkSXlNixo',
    appId: '1:428238808676:android:0c810490f2d786fcb72171',
    messagingSenderId: '428238808676',
    projectId: 'to-do-application-6d1ef',
    storageBucket: 'to-do-application-6d1ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFPl7w-k4S1jkIfhY9cRAWz1WGi06TpJ4',
    appId: '1:428238808676:ios:578dff52d69fcdc9b72171',
    messagingSenderId: '428238808676',
    projectId: 'to-do-application-6d1ef',
    storageBucket: 'to-do-application-6d1ef.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFPl7w-k4S1jkIfhY9cRAWz1WGi06TpJ4',
    appId: '1:428238808676:ios:d3296c88c7eb64ddb72171',
    messagingSenderId: '428238808676',
    projectId: 'to-do-application-6d1ef',
    storageBucket: 'to-do-application-6d1ef.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
